version: "3.8"

services:
  db:
    container_name: pokit-mysql-local
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pokit
      TZ: Asia/Seoul
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
