rootProject.name = "pokit"
include("domain")
include("application")
include("entry")
include("entry:web")
include("entry:batch")
include("adapters")
include("adapters:in-web")
include("adapters:in-batch")
include("adapters:out-persistence")
include("adapters:out-cache")
include("adapters:out-web")
